//
//  geopackage-ios.h
//  geopackage-ios
//
//  Created by Brian Osborn on 9/1/15.
//  Copyright (c) 2015 NGA. All rights reserved.
//

#import <UIKit/UIKit.h>

//! Project version number for geopackage-ios.
FOUNDATION_EXPORT double geopackage_iosVersionNumber;

//! Project version string for geopackage-ios.
FOUNDATION_EXPORT const unsigned char geopackage_iosVersionString[];

// In this header, you should import all the public headers of your framework using statements like #import <geopackage_ios/PublicHeader.h>


#import <GeoPackage/GPKGBoundingBox.h>
#import <GeoPackage/GPKGDateConverter.h>
#import <GeoPackage/GPKGGeoPackage.h>
#import <GeoPackage/GPKGGeoPackageCache.h>
#import <GeoPackage/GPKGGeoPackageConstants.h>
#import <GeoPackage/GPKGUtils.h>
#import <GeoPackage/GPKGAttributesColumn.h>
#import <GeoPackage/GPKGAttributesDao.h>
#import <GeoPackage/GPKGAttributesRow.h>
#import <GeoPackage/GPKGAttributesTable.h>
#import <GeoPackage/GPKGAttributesTableReader.h>
#import <GeoPackage/GPKGContents.h>
#import <GeoPackage/GPKGContentsDao.h>
#import <GeoPackage/GPKGContentsDataTypes.h>
#import <GeoPackage/GPKGSpatialReferenceSystem.h>
#import <GeoPackage/GPKGSpatialReferenceSystemDao.h>
#import <GeoPackage/GPKGAlterTable.h>
#import <GeoPackage/GPKGConnection.h>
#import <GeoPackage/GPKGConnectionFunction.h>
#import <GeoPackage/GPKGDataTypes.h>
#import <GeoPackage/GPKGFeatureIndexer.h>
#import <GeoPackage/GPKGGeoPackageTableCreator.h>
#import <GeoPackage/GPKGMappedColumn.h>
#import <GeoPackage/GPKGResultSet.h>
#import <GeoPackage/GPKGSqlLiteQueryBuilder.h>
#import <GeoPackage/GPKGSqlUtils.h>
#import <GeoPackage/GPKGTableCreator.h>
#import <GeoPackage/GPKGTableMapping.h>
#import <GeoPackage/GPKGBaseDao.h>
#import <GeoPackage/GPKGColumnRange.h>
#import <GeoPackage/GPKGColumnValue.h>
#import <GeoPackage/GPKGColumnValues.h>
#import <GeoPackage/GPKGSQLiteMaster.h>
#import <GeoPackage/GPKGSQLiteMasterColumns.h>
#import <GeoPackage/GPKGSQLiteMasterQuery.h>
#import <GeoPackage/GPKGSQLiteMasterTypes.h>
#import <GeoPackage/GPKGGeoPackageMetadata.h>
#import <GeoPackage/GPKGGeoPackageMetadataDao.h>
#import <GeoPackage/GPKGGeoPackageMetadataTableCreator.h>
#import <GeoPackage/GPKGGeometryMetadata.h>
#import <GeoPackage/GPKGGeometryMetadataDao.h>
#import <GeoPackage/GPKGMetadataDb.h>
#import <GeoPackage/GPKGTableMetadata.h>
#import <GeoPackage/GPKGTableMetadataDao.h>
#import <GeoPackage/GPKGConnectionPool.h>
#import <GeoPackage/GPKGDbConnection.h>
#import <GeoPackage/GPKGSqliteConnection.h>
#import <GeoPackage/GPKGColumnConstraints.h>
#import <GeoPackage/GPKGConstraint.h>
#import <GeoPackage/GPKGConstraintParser.h>
#import <GeoPackage/GPKGConstraintTypes.h>
#import <GeoPackage/GPKGRawConstraint.h>
#import <GeoPackage/GPKGTableColumn.h>
#import <GeoPackage/GPKGTableConstraints.h>
#import <GeoPackage/GPKGTableInfo.h>
#import <GeoPackage/GPKGUniqueConstraint.h>
#import <GeoPackage/GPKGBaseExtension.h>
#import <GeoPackage/GPKGCrsWktExtension.h>
#import <GeoPackage/GPKGCrsWktExtensionVersions.h>
#import <GeoPackage/GPKGExtensions.h>
#import <GeoPackage/GPKGExtensionsDao.h>
#import <GeoPackage/GPKGFeatureIndexRTreeResults.h>
#import <GeoPackage/GPKGExtensionManager.h>
#import <GeoPackage/GPKGGeometryExtensions.h>
#import <GeoPackage/GPKGMetadataExtension.h>
#import <GeoPackage/GPKGNGAExtensions.h>
#import <GeoPackage/GPKGRTreeIndexExtension.h>
#import <GeoPackage/GPKGRTreeIndexTableDao.h>
#import <GeoPackage/GPKGRTreeIndexTableRow.h>
#import <GeoPackage/GPKGSchemaExtension.h>
#import <GeoPackage/GPKGWebPExtension.h>
#import <GeoPackage/GPKGZoomOtherExtension.h>
#import <GeoPackage/GPKGContentsId.h>
#import <GeoPackage/GPKGContentsIdDao.h>
#import <GeoPackage/GPKGContentsIdExtension.h>
#import <GeoPackage/GPKGCoverageData.h>
#import <GeoPackage/GPKGCoverageDataAlgorithms.h>
#import <GeoPackage/GPKGCoverageDataImage.h>
#import <GeoPackage/GPKGCoverageDataPng.h>
#import <GeoPackage/GPKGCoverageDataPngImage.h>
#import <GeoPackage/GPKGCoverageDataRequest.h>
#import <GeoPackage/GPKGCoverageDataResults.h>
#import <GeoPackage/GPKGCoverageDataSourcePixel.h>
#import <GeoPackage/GPKGCoverageDataTiff.h>
#import <GeoPackage/GPKGCoverageDataTiffImage.h>
#import <GeoPackage/GPKGCoverageDataTileMatrixResults.h>
#import <GeoPackage/GPKGGriddedCoverage.h>
#import <GeoPackage/GPKGGriddedCoverageDao.h>
#import <GeoPackage/GPKGGriddedCoverageDataTypes.h>
#import <GeoPackage/GPKGGriddedCoverageEncodingTypes.h>
#import <GeoPackage/GPKGGriddedTile.h>
#import <GeoPackage/GPKGGriddedTileDao.h>
#import <GeoPackage/GPKGFeatureTableIndex.h>
#import <GeoPackage/GPKGGeometryIndex.h>
#import <GeoPackage/GPKGGeometryIndexDao.h>
#import <GeoPackage/GPKGTableIndex.h>
#import <GeoPackage/GPKGTableIndexDao.h>
#import <GeoPackage/GPKGFeatureTileLink.h>
#import <GeoPackage/GPKGFeatureTileLinkDao.h>
#import <GeoPackage/GPKGFeatureTileTableLinker.h>
#import <GeoPackage/GPKGPropertiesExtension.h>
#import <GeoPackage/GPKGPropertiesManager.h>
#import <GeoPackage/GPKGPropertyNames.h>
#import <GeoPackage/GPKGExtendedRelation.h>
#import <GeoPackage/GPKGExtendedRelationsDao.h>
#import <GeoPackage/GPKGRelatedTablesExtension.h>
#import <GeoPackage/GPKGRelationTypes.h>
#import <GeoPackage/GPKGUserMappingDao.h>
#import <GeoPackage/GPKGUserMappingRow.h>
#import <GeoPackage/GPKGUserMappingTable.h>
#import <GeoPackage/GPKGUserRelatedTable.h>
#import <GeoPackage/GPKGDublinCoreMetadata.h>
#import <GeoPackage/GPKGDublinCoreTypes.h>
#import <GeoPackage/GPKGMediaDao.h>
#import <GeoPackage/GPKGMediaRow.h>
#import <GeoPackage/GPKGMediaTable.h>
#import <GeoPackage/GPKGSimpleAttributesDao.h>
#import <GeoPackage/GPKGSimpleAttributesRow.h>
#import <GeoPackage/GPKGSimpleAttributesTable.h>
#import <GeoPackage/GPKGTileScaling.h>
#import <GeoPackage/GPKGTileScalingDao.h>
#import <GeoPackage/GPKGTileScalingTypes.h>
#import <GeoPackage/GPKGTileTableScaling.h>
#import <GeoPackage/GPKGFeatureStyle.h>
#import <GeoPackage/GPKGFeatureStyleExtension.h>
#import <GeoPackage/GPKGFeatureStyles.h>
#import <GeoPackage/GPKGFeatureTableStyles.h>
#import <GeoPackage/GPKGIconCache.h>
#import <GeoPackage/GPKGIconDao.h>
#import <GeoPackage/GPKGIconRow.h>
#import <GeoPackage/GPKGIconTable.h>
#import <GeoPackage/GPKGIcons.h>
#import <GeoPackage/GPKGStyleDao.h>
#import <GeoPackage/GPKGStyleMappingDao.h>
#import <GeoPackage/GPKGStyleMappingRow.h>
#import <GeoPackage/GPKGStyleMappingTable.h>
#import <GeoPackage/GPKGStyleRow.h>
#import <GeoPackage/GPKGStyleTable.h>
#import <GeoPackage/GPKGStyles.h>
#import <GeoPackage/GPKGGeoPackageFactory.h>
#import <GeoPackage/GPKGGeoPackageManager.h>
#import <GeoPackage/GPKGSessionTaskData.h>
#import <GeoPackage/GPKGFeatureGenerator.h>
#import <GeoPackage/GPKGOAPIFeatureGenerator.h>
#import <GeoPackage/GPKGGeometryColumns.h>
#import <GeoPackage/GPKGGeometryColumnsDao.h>
#import <GeoPackage/GPKGFeatureIndexFeatureResults.h>
#import <GeoPackage/GPKGFeatureIndexGeoPackageResults.h>
#import <GeoPackage/GPKGFeatureIndexListResults.h>
#import <GeoPackage/GPKGFeatureIndexManager.h>
#import <GeoPackage/GPKGFeatureIndexMetadataResults.h>
#import <GeoPackage/GPKGFeatureIndexResultSetResults.h>
#import <GeoPackage/GPKGFeatureIndexResults.h>
#import <GeoPackage/GPKGFeatureIndexTypes.h>
#import <GeoPackage/GPKGMultipleFeatureIndexResults.h>
#import <GeoPackage/GPKGFeatureCache.h>
#import <GeoPackage/GPKGFeatureCacheTables.h>
#import <GeoPackage/GPKGFeatureColumn.h>
#import <GeoPackage/GPKGFeatureDao.h>
#import <GeoPackage/GPKGFeatureRow.h>
#import <GeoPackage/GPKGFeatureTable.h>
#import <GeoPackage/GPKGFeatureTableReader.h>
#import <GeoPackage/GPKGManualFeatureQuery.h>
#import <GeoPackage/GPKGManualFeatureQueryResults.h>
#import <GeoPackage/GPKGGeometryData.h>
#import <GeoPackage/GPKGGeometryUtils.h>
#import <GeoPackage/GPKGFeatureShape.h>
#import <GeoPackage/GPKGFeatureShapes.h>
#import <GeoPackage/GPKGLocationBoundingBox.h>
#import <GeoPackage/GPKGMapPoint.h>
#import <GeoPackage/GPKGMapPointInitializer.h>
#import <GeoPackage/GPKGMapPointOptions.h>
#import <GeoPackage/GPKGMapShape.h>
#import <GeoPackage/GPKGMapShapeConverter.h>
#import <GeoPackage/GPKGMapShapePoints.h>
#import <GeoPackage/GPKGMapShapeTypes.h>
#import <GeoPackage/GPKGMultiPoint.h>
#import <GeoPackage/GPKGMultiPolygon.h>
#import <GeoPackage/GPKGMultiPolygonPoints.h>
#import <GeoPackage/GPKGMultiPolyline.h>
#import <GeoPackage/GPKGMultiPolylinePoints.h>
#import <GeoPackage/GPKGPolygon.h>
#import <GeoPackage/GPKGPolygonHolePoints.h>
#import <GeoPackage/GPKGPolygonOptions.h>
#import <GeoPackage/GPKGPolygonOrientations.h>
#import <GeoPackage/GPKGPolygonPoints.h>
#import <GeoPackage/GPKGPolyline.h>
#import <GeoPackage/GPKGPolylineOptions.h>
#import <GeoPackage/GPKGPolylinePoints.h>
#import <GeoPackage/GPKGShapePoints.h>
#import <GeoPackage/GPKGShapeWithChildrenPoints.h>
#import <GeoPackage/GPKGCompressFormats.h>
#import <GeoPackage/GPKGIOUtils.h>
#import <GeoPackage/GPKGImageConverter.h>
#import <GeoPackage/GPKGProgress.h>
#import <GeoPackage/GPKGMapTolerance.h>
#import <GeoPackage/GPKGMapUtils.h>
#import <GeoPackage/GPKGFeatureInfoBuilder.h>
#import <GeoPackage/GPKGStyleCache.h>
#import <GeoPackage/GPKGStyleUtils.h>
#import <GeoPackage/GPKGMetadata.h>
#import <GeoPackage/GPKGMetadataDao.h>
#import <GeoPackage/GPKGMetadataScope.h>
#import <GeoPackage/GPKGMetadataReference.h>
#import <GeoPackage/GPKGMetadataReferenceDao.h>
#import <GeoPackage/GPKGProperties.h>
#import <GeoPackage/GPKGPropertyConstants.h>
#import <GeoPackage/GPKGDataColumns.h>
#import <GeoPackage/GPKGDataColumnsDao.h>
#import <GeoPackage/GPKGDataColumnConstraints.h>
#import <GeoPackage/GPKGDataColumnConstraintsDao.h>
#import <GeoPackage/GPKGTileBoundingBoxUtils.h>
#import <GeoPackage/GPKGTileGenerator.h>
#import <GeoPackage/GPKGTileGrid.h>
#import <GeoPackage/GPKGTileUtils.h>
#import <GeoPackage/GPKGUrlTileGenerator.h>
#import <GeoPackage/GPKGCustomFeaturesTile.h>
#import <GeoPackage/GPKGFeatureTileContext.h>
#import <GeoPackage/GPKGFeatureTileGenerator.h>
#import <GeoPackage/GPKGFeatureTilePointIcon.h>
#import <GeoPackage/GPKGFeatureTiles.h>
#import <GeoPackage/GPKGNumberFeaturesTile.h>
#import <GeoPackage/GPKGTileMatrix.h>
#import <GeoPackage/GPKGTileMatrixDao.h>
#import <GeoPackage/GPKGTileMatrixSet.h>
#import <GeoPackage/GPKGTileMatrixSetDao.h>
#import <GeoPackage/GPKGBoundedOverlay.h>
#import <GeoPackage/GPKGCompositeOverlay.h>
#import <GeoPackage/GPKGFeatureOverlay.h>
#import <GeoPackage/GPKGFeatureOverlayQuery.h>
#import <GeoPackage/GPKGFeatureRowData.h>
#import <GeoPackage/GPKGFeatureTableData.h>
#import <GeoPackage/GPKGGeoPackageOverlay.h>
#import <GeoPackage/GPKGOverlayFactory.h>
#import <GeoPackage/GPKGXYZOverlay.h>
#import <GeoPackage/GPKGGeoPackageTile.h>
#import <GeoPackage/GPKGGeoPackageTileRetriever.h>
#import <GeoPackage/GPKGXYZTileRetriever.h>
#import <GeoPackage/GPKGTileCreator.h>
#import <GeoPackage/GPKGTileRetriever.h>
#import <GeoPackage/GPKGTileColumn.h>
#import <GeoPackage/GPKGTileDao.h>
#import <GeoPackage/GPKGTileDaoUtils.h>
#import <GeoPackage/GPKGTileRow.h>
#import <GeoPackage/GPKGTileTable.h>
#import <GeoPackage/GPKGTileTableReader.h>
#import <GeoPackage/GPKGContentValues.h>
#import <GeoPackage/GPKGUserColumn.h>
#import <GeoPackage/GPKGUserDao.h>
#import <GeoPackage/GPKGUserRow.h>
#import <GeoPackage/GPKGUserRowSync.h>
#import <GeoPackage/GPKGUserTable.h>
#import <GeoPackage/GPKGUserTableReader.h>
#import <GeoPackage/GPKGUserCustomColumn.h>
#import <GeoPackage/GPKGUserCustomDao.h>
#import <GeoPackage/GPKGUserCustomRow.h>
#import <GeoPackage/GPKGUserCustomTable.h>
#import <GeoPackage/GPKGUserCustomTableReader.h>
#import <GeoPackage/GPKGGeoPackageValidate.h>
#import <GeoPackage/GPKGUserColumns.h>
#import <GeoPackage/GPKGAttributesColumns.h>
#import <GeoPackage/GPKGFeatureColumns.h>
#import <GeoPackage/GPKGTileColumns.h>
#import <GeoPackage/GPKGUserCustomColumns.h>
#import <GeoPackage/GPKGFeatureIndexLocation.h>
#import <GeoPackage/GPKGFeatureIndexerIdQuery.h>
#import <GeoPackage/GPKGFeatureIndexerIdResultSet.h>
#import <GeoPackage/GPKGFeaturePreview.h>
#import <GeoPackage/GPKGUserTableMetadata.h>
#import <GeoPackage/GPKGAttributesTableMetadata.h>
#import <GeoPackage/GPKGConstraints.h>
#import <GeoPackage/GPKGExtensionManagement.h>
#import <GeoPackage/GPKGContentsIdTableCreator.h>
#import <GeoPackage/GPKGGeometryIndexTableCreator.h>
#import <GeoPackage/GPKGFeatureTileLinkTableCreator.h>
#import <GeoPackage/GPKGTileScalingTableCreator.h>
#import <GeoPackage/GPKGMediaTableMetadata.h>
#import <GeoPackage/GPKGSimpleAttributesTableMetadata.h>
#import <GeoPackage/GPKGFeatureTableMetadata.h>
#import <GeoPackage/GPKGTileTableMetadata.h>
#import <GeoPackage/GPKGNGATableCreator.h>
#import <GeoPackage/GPKGTileReprojection.h>
#import <GeoPackage/GPKGTileReprojectionZoom.h>
#import <GeoPackage/GPKGTileReprojectionOptimize.h>
#import <GeoPackage/GPKGPlatteCarreOptimize.h>
#import <GeoPackage/GPKGWebMercatorOptimize.h>
#import <GeoPackage/GPKGNetworkUtils.h>
#import <GeoPackage/GPKGRow.h>
#import <GeoPackage/GPKGObjectResultSet.h>
#import <GeoPackage/GPKGRowResultSet.h>
#import <GeoPackage/GPKGPagination.h>
#import <GeoPackage/GPKGPaginatedResults.h>
#import <GeoPackage/GPKGObjectPaginatedResults.h>
#import <GeoPackage/GPKGRowPaginatedResults.h>
#import <GeoPackage/GPKGPixelBounds.h>
#import <GeoPackage/GPKGGeometryCrop.h>
#import <GeoPackage/GPKGDgiwgConstants.h>
#import <GeoPackage/GPKGDgiwgCoordinateReferenceSystems.h>
#import <GeoPackage/GPKGDgiwgDataTypes.h>
#import <GeoPackage/GPKGDgiwgGeoPackage.h>
#import <GeoPackage/GPKGDgiwgGeoPackageFactory.h>
#import <GeoPackage/GPKGDgiwgGeoPackageManager.h>
#import <GeoPackage/GPKGDgiwgMetadata.h>
#import <GeoPackage/GPKGDgiwgRequirements.h>
#import <GeoPackage/GPKGDgiwgValidate.h>
#import <GeoPackage/GPKGDgiwgValidationError.h>
#import <GeoPackage/GPKGDgiwgValidationErrors.h>
#import <GeoPackage/GPKGDgiwgValidationKey.h>
#import <GeoPackage/GPKGDgiwgFile.h>
#import <GeoPackage/GPKGDgiwgFileName.h>
#import <GeoPackage/GPKGDgiwgUtils.h>
#import <GeoPackage/GPKGDgiwgWellKnownText.h>
#import <GeoPackage/GPKGUTMZone.h>
